pcap_files:
  - "/home/vairav-babin/localdisk-c/etc/AD/pcap-scanner/pcap-src/host_2_capture.pcap"
  - "/home/vairav-babin/localdisk-c/etc/AD/pcap-scanner/pcap-src/host_capture.pcap"
log_level: debug
log_file: "scanner.log"
