pcap_files:
  - "/home/vairav-babin/localdisk-c/etc/AD/pcap-analysis/pcap-src/12_packet.pcap"
  # - "/home/vairav-babin/localdisk-c/etc/AD/pcap-analysis/pcap-src/host_capture.pcap"
log_level: debug
log_file: "scanner.log"
